#!/bin/bash
pip install numpy matplotlib

git clone https://github.com/mrphysics-bonn/spiral-pypulseq-example
cd spiral-pypulseq-example/spiraltraj
python setup.py install

git clone --single-branch --branch dev https://github.com/imr-framework/pypulseq
cd pypulseq
git switch checkout 2548f0d
python setup.py install

git clone https://github.com/ismrmrd/ismrmrd-python.git
cd ismrmrd-python
git checkout v1.9.3
pip install .
