#!/bin/bash
pip install numpy matplotlib

git clone https://github.com/mrphysics-bonn/spiral-pypulseq-example
cd spiral-pypulseq-example/spiraltraj
python setup.py install

git clone --single-branch --branch binder_compatibility https://github.com/mavel101/pypulseq.git
cd pypulseq
python setup.py install

git clone https://github.com/ismrmrd/ismrmrd-python.git
cd ismrmrd-python
python setup.py install
